steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/pipelinetest-355200/github.com/mokubatek/pipeline:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/pipelinetest-355200/github.com/mokubatek/pipeline:$SHORT_SHA']
